name: 256LOL
highlighter: rouge
timezone: America/New_York
future: true
exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
include:
  - "_posts"
  - "code"
plugins:
  - github-pages
markdown: kramdown
